services:
  fastapi-backend: 
    build: ./fastapi-backend
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      
  nestjs-backend:
    build: ./nestjs-backend
    ports:
      - "3001:3001"
    environment:
      - FASTAPI_URL=http://fastapi-backend:8000
      - REDIS_URL=redis://redis:6379
    depends_on:
      - fastapi-backend
      - redis
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      
  nextjs-frontend:
    build: ./nextjs-frontend
    ports:
      - "3000:3000"
    depends_on:
      - nestjs-backend
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
    